version: 0.1
phases:
    install:
        commands:
        - ls -al
        - pwd
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    webapp:
      base-directory: packages/website/dist
      files:
        - '**/*'
      name: webapp
